name: CICD
on:
  push:
    branches:
      - 'release'
jobs:
  build:
    name: build flutter
    runs-on: macos-11
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.8.1"
    steps:
      - uses: actions/checkout@v2
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AFTERNOON_WORKSHOP }}"
          projectId: afternoon-workshop
          channelId: live